# -*- coding: utf-8 -*-
"""AI510-TP02-T03-System-Architecture-Diagrams-Resume-to-Job-Application.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D3dL9eCnYnaK0U7Gae1Uyif-i0RbdDcF

# Resume-to-Job: A Retrieval-Augmented Web Application for Matching and Grading Computer Science Graduate Subsequently Resumes Against LinkedIn Job Postings

**Akzhol Suborov · Ruojie (Jack) Hao · Khanh Duy (Dean) Bui · Do Minh Quan (Enzo) Nguyen · Enkhamgalan (Enkh) Baterdene**

**Team T03 — AI 510:** Artificial Intelligence in Cloud Computing  
*Master of Science in Computer Science, School of Technology & Computing*  
*City University of Seattle, Seattle, WA, USA*  

`suborovakzhol@cityuniversity.edu` | `haoruojie@cityuniversity.edu` | `buikhanhduy@cityuniversity.edu` | `nguyendominhquan@cityuniversity.edu` | `baterdeneenkhamgala@cityuniversity.edu`

# High-Resolution Mermaid Diagrams for Team Project

This notebook takes text instructions for Mermaid diagrams and renders them as high-resolution images within the output cells. It uses an external rendering service (`mermaid.ink`) to generate the images.

## Setup

Run the following cell to define the rendering function.
"""

import json
import base64
from IPython.display import Image, display

def render_mermaid(mermaid_code, theme='default', bg_color='white'):
    """
    Renders a Mermaid diagram from text instructions using mermaid.ink.

    Args:
        mermaid_code (str): The Mermaid diagram syntax.
        theme (str): The theme for the diagram (e.g., 'default', 'forest', 'dark', 'neutral').
        bg_color (str): The background color of the image (e.g., 'white', 'transparent').
    """
    try:
        # Use json.dumps to properly construct and escape the JSON payload
        payload_dict = {
            "code": mermaid_code,
            "mermaid": {
                "theme": theme,
                "themeVariables": {
                    "background": bg_color
                }
            }
        }
        payload_json = json.dumps(payload_dict)

        # Encode the payload to base64 safely
        base64_bytes = base64.b64encode(payload_json.encode('utf-8'))
        base64_string = base64_bytes.decode('utf-8')

        # Construct the URL for the image request
        # Using the /img endpoint provides a static image
        url = f"https://mermaid.ink/img/{base64_string}"

        # Display the image in the notebook cell
        display(Image(url=url))

    except Exception as e:
        print(f"An error occurred while rendering the diagram: {e}")

"""## Diagram 1"""

# Commented out IPython magic to ensure Python compatibility.
# # Paste your Mermaid instructions for Diagram 1 between the triple quotes
# diagram_1_text = """
# 
# %% Resume-to-Job - System Context (C4 Level 1)
# %% Reflects v1 current code (CityU AI 510, Spring 2026, Week 07).
# %% Entry point: src/ui/app.py  |  Render: mmdc -i 01-system-context.mmd -o 01-system-context.png
# flowchart TB
#     student["CS Graduate Student<br/>(job seeker)"]
# 
#     subgraph system["Resume-to-Job System (Streamlit web app)"]
#         app["Resume-to-Job application<br/>ingest - embed - match - grade"]
#     end
# 
#     subgraph assets["Local / bundled assets"]
#         model["all-MiniLM-L6-v2<br/>sentence-transformers model<br/>(offline embeddings)"]
#         db[("SQLite database<br/>data/jobs.sqlite3")]
#     end
# 
#     arbeitnow["LinkedIn job listings<br/>(custom Power Automate scrape /<br/>paid job API)"]
#     gemini["Google Gemini API<br/>gemini-2.5-flash<br/>(BYOK: user supplies key)"]
# 
#     student -->|"upload resume PDF / paste text,<br/>enter Gemini API key"| app
#     app -->|"top job matches + AI grade"| student
#     app -->|"import LinkedIn job listings"| arbeitnow
#     app -->|"prompt: resume + top 3 jobs"| gemini
#     gemini -->|"structured JSON grade"| app
#     app -->|"encode text to 384-d vectors"| model
#     app -->|"store / query jobs + embeddings"| db
# 
# 
# 
# """
# 
# render_mermaid(diagram_1_text)
#

"""## Diagram 2"""

# Commented out IPython magic to ensure Python compatibility.
# # Paste your Mermaid instructions for Diagram 2 between the triple quotes
# diagram_2_text = """
# %% Resume-to-Job - Hexagonal (Ports and Adapters) Architecture
# %% The core domain depends only on Ports (interfaces). Adapters implement the ports.
# %% Dependencies point inward: UI -> Core <- Adapters.
# flowchart LR
#     subgraph driving["Driving side (primary adapter)"]
#         ui["Streamlit UI<br/>src/ui/app.py + pages/*"]
#     end
# 
#     subgraph core["Core domain - src/core (framework-free)"]
#         orch["Orchestrator"]
#         ing_svc["IngestionService"]
#         match_svc["MatchingService"]
#         grade_svc["GradingService"]
#         tok["token_counter"]
# 
#         subgraph ports["Ports (interfaces) - src/core/ports"]
#             p_ing["IngestionPort"]
#             p_repo["JobRepositoryPort"]
#             p_embed["EmbeddingPort"]
#             p_rag["RagPort"]
#             p_grade["GradingPort"]
#             p_pdftext["PdfTextPort"]
#         end
#     end
# 
#     subgraph driven["Driven side (secondary adapters) - src/adapters"]
#         a_arb["Job ingestion adapter<br/>(Power Automate dataset / job API)"]
#         a_repo["SQLiteJobRepository"]
#         a_embed["LocalEmbedder"]
#         a_rag["RagService + SimilaritySearch"]
#         a_gem["GeminiClient + json_parser"]
#         a_pdftext["PdfTextExtractor"]
#     end
# 
#     subgraph ext["External systems"]
#         e_arb["LinkedIn data<br/>(Power Automate / API)"]
#         e_db[("SQLite file")]
#         e_model["MiniLM model"]
#         e_gem["Gemini API"]
#     end
# 
#     ui --> orch
#     orch --> ing_svc
#     orch --> match_svc
#     orch --> grade_svc
#     match_svc --> tok
# 
#     ing_svc --> p_ing
#     ing_svc --> p_repo
#     ing_svc --> p_embed
#     match_svc --> p_repo
#     match_svc --> p_rag
#     grade_svc --> p_grade
#     orch --> p_pdftext
# 
#     p_ing -. implemented by .-> a_arb
#     p_repo -. implemented by .-> a_repo
#     p_embed -. implemented by .-> a_embed
#     p_rag -. implemented by .-> a_rag
#     p_grade -. implemented by .-> a_gem
#     p_pdftext -. implemented by .-> a_pdftext
# 
#     a_arb --> e_arb
#     a_repo --> e_db
#     a_embed --> e_model
#     a_gem --> e_gem
#     a_rag --> a_repo
#     a_rag --> a_embed
# 
# """
# 
# render_mermaid(diagram_2_text, theme='forest')
#

"""## Diagram 3"""

# Commented out IPython magic to ensure Python compatibility.
# # Paste your Mermaid instructions for Diagram 3 between the triple quotes
# diagram_3_text = """
# %% Resume-to-Job - Component & Module View (v1)
# %% NOTE: dashboard.py and resume_builder.py page render() functions are stubs in v1
# %% (return pass). They are planned for v2 per the team.
# flowchart TB
#     subgraph ui_layer["Presentation - src/ui"]
#         app["app.py<br/>composition root + sidebar (st.radio) + BYOK key"]
#         pg_match["pages/job_matching.py - functional"]
#         pg_admin["pages/admin_ingest.py - functional"]
#         pg_dash["pages/dashboard.py - STUB (planned v2)"]
#         pg_resume["pages/resume_builder.py - STUB (planned v2)"]
#     end
# 
#     subgraph cfg["Config - src/config"]
#         settings["settings.py<br/>top_k=15 - model paths - gemini-2.5-flash"]
#     end
# 
#     subgraph core_layer["Core - src/core"]
#         orch["Orchestrator"]
#         ing["IngestionService"]
#         mat["MatchingService"]
#         grd["GradingService"]
#         tok["token_counter"]
#     end
# 
#     subgraph adapters_layer["Adapters - src/adapters"]
#         arb["ingestion/job source adapter<br/>(Power Automate / API)"]
#         repo["db/SQLiteJobRepository"]
#         emb["rag/LocalEmbedder"]
#         rag["rag/RagService + similarity"]
#         gem["grading/GeminiClient + json_parser"]
#         pdftext["pdf/PdfTextExtractor"]
#     end
# 
#     app --> settings
#     app --> orch
#     app --> pg_match
#     app --> pg_admin
#     app --> pg_dash
#     app --> pg_resume
# 
#     pg_admin --> orch
#     pg_match --> orch
#     pg_match --> pdftext
# 
#     orch --> ing
#     orch --> mat
#     orch --> grd
#     mat --> tok
# 
#     ing --> arb
#     ing --> repo
#     ing --> emb
#     mat --> repo
#     mat --> rag
#     grd --> gem
#     rag --> repo
#     rag --> emb
# 
# """
# 
# render_mermaid(diagram_3_text, theme='dark', bg_color='black')
#

"""## Diagram 4"""

# Commented out IPython magic to ensure Python compatibility.
# # Paste your Mermaid instructions for Diagram 4 between the triple quotes
# diagram_4_text = """
# %% Resume-to-Job - Job Ingestion Sequence (Admin / Ingest page)
# sequenceDiagram
#     actor U as Student/Admin
#     participant Pg as admin_ingest.py
#     participant O as Orchestrator
#     participant IS as IngestionService
#     participant AC as Job source adapter
#     participant API as LinkedIn data (Power Automate / API)
#     participant EM as LocalEmbedder
#     participant DB as SQLiteJobRepository
# 
#     U->>Pg: enter query + pages, click "Trigger Ingestion"
#     Pg->>O: ingest_jobs(query, max_pages)
#     O->>IS: run(query) via ingestion_factory
#     IS->>DB: initialize() - CREATE TABLE IF NOT EXISTS
#     IS->>AC: fetch_jobs(query)
#     loop for each page 1..max_pages
#         AC->>API: fetch listings (export / API page n)
#         API-->>AC: JSON job listings
#     end
#     AC-->>IS: list[Job] normalized + query-filtered
#     IS->>EM: embed_texts(descriptions)
#     EM-->>IS: list of float32 vectors (384-d)
#     IS->>DB: upsert_jobs(jobs, embeddings) ON CONFLICT
#     DB-->>IS: upserted count
#     IS->>DB: count_jobs()
#     DB-->>IS: total
#     IS-->>O: IngestionSummary(fetched, upserted, total)
#     O-->>Pg: summary + metrics (fetch_ms, embed_ms, upsert_ms)
#     Pg-->>U: success message + metrics + console logs
# 
# """
# 
# render_mermaid(diagram_4_text)
#

"""## Diagram 5"""

# Commented out IPython magic to ensure Python compatibility.
# # Paste your Mermaid instructions for Diagram 5 between the triple quotes
# diagram_5_text = """
# %% Resume-to-Job - Resume Matching Sequence (Job Matching page)
# %% Gate: matching only runs when available embeddings >= limit * 10
# %% (MatchingService.min_embeddings_multiplier = 10; default limit 15 -> needs 150).
# sequenceDiagram
#     actor U as Student
#     participant Pg as job_matching.py
#     participant PX as PdfTextExtractor
#     participant O as Orchestrator
#     participant MS as MatchingService
#     participant DB as SQLiteJobRepository
#     participant RS as RagService
#     participant EM as LocalEmbedder
#     participant SIM as SimilaritySearch
#     participant TOK as token_counter
# 
#     U->>Pg: upload resume PDF (or paste text), click "Find matches"
#     opt PDF uploaded
#         Pg->>PX: extract_text(pdf_bytes)
#         PX-->>Pg: resume_text
#     end
#     Pg->>O: match_jobs(resume_text, limit)
#     O->>MS: match_resume(resume_text, limit)
#     MS->>DB: count_embeddings()
#     DB-->>MS: available
#     alt available < limit * 10
#         MS-->>Pg: MatchSummary(ready=false, message)
#         Pg-->>U: warning - not enough embedded jobs
#     else enough embeddings
#         MS->>RS: top_matches(resume_text, limit)
#         RS->>EM: embed_text(resume_text)
#         EM-->>RS: query vector (384-d)
#         RS->>DB: fetch_embeddings()
#         DB-->>RS: list of (job_id, bytes)
#         RS->>SIM: top_matches(vectors, query, limit)
#         SIM-->>RS: list of (job_id, score) sorted desc
#         RS-->>MS: top matches
#         MS->>DB: fetch_jobs_by_ids(job_ids)
#         DB-->>MS: list[Job]
#         MS->>TOK: estimate_grading_tokens(resume, jobs)
#         TOK-->>MS: TokenEstimate
#         MS-->>Pg: MatchSummary(matches, jobs, metrics)
#         Pg-->>U: ranked top-N matches + metrics
#     end
# 
# """
# 
# render_mermaid(diagram_5_text, theme='neutral')
#

"""## Diagram 6"""

# Commented out IPython magic to ensure Python compatibility.
# # Paste your Mermaid instructions for Diagram 6 between the triple quotes
# diagram_6_text = """
# %% Resume-to-Job - AI Grading Sequence (Job Matching page -> Gemini)
# %% Only the top 3 matched jobs are sent for grading (build_grading_job_payloads limit=3).
# sequenceDiagram
#     actor U as Student
#     participant Pg as job_matching.py
#     participant O as Orchestrator
#     participant GF as grading_factory
#     participant GS as GradingService
#     participant GC as GeminiClient
#     participant TOK as token_counter
#     participant API as Gemini API gemini-2.5-flash
#     participant JP as json_parser
# 
#     U->>Pg: click "Grade with AI"
#     alt no Gemini API key in sidebar
#         Pg-->>U: warning - enter a Gemini API key
#     else key present
#         Pg->>O: read grading_factory
#         O-->>Pg: grading_factory
#         Pg->>GF: grading_factory(api_key)
#         GF-->>Pg: GradingService wrapping GeminiClient
#         Pg->>GS: grade_resume(resume_text, top 3 job descriptions)
#         GS->>GC: grade(resume_text, job_descriptions)
#         GC->>TOK: build_grading_prompt(resume, jobs)
#         TOK-->>GC: prompt with strict JSON schema
#         GC->>API: generate_content(prompt, temperature=0.2)
#         API-->>GC: response text
#         GC->>JP: parse_grade_json(text)
#         JP-->>GC: validated dict (required keys checked)
#         GC-->>GS: GradeResult(overall, strengths, gaps, recs, top_jobs)
#         GS-->>Pg: GradeResult
#         Pg-->>U: overall grade + per-job grades + recommendations
#     end
# 
# """
# 
# render_mermaid(diagram_6_text)
#

"""## Diagram 7"""

# Commented out IPython magic to ensure Python compatibility.
# # Paste your Mermaid instructions for Diagram 7 between the triple quotes
# diagram_7_text = """
# %% Resume-to-Job - Data Model (SQLite: data/jobs.sqlite3)
# %% Single-table design. The embedding is stored inline as a float32 BLOB.
# %% There is NO vector index: similarity is a full scan + NumPy cosine in Python.
# %% Connection uses PRAGMA journal_mode=WAL and synchronous=NORMAL.
# erDiagram
#     JOBS {
#         TEXT job_id PK "slug or sha256 hash of title+company+url"
#         TEXT title "NOT NULL"
#         TEXT company "NOT NULL"
#         TEXT description "NOT NULL - this text is embedded"
#         TEXT location "nullable"
#         TEXT job_type "nullable"
#         TEXT salary "nullable"
#         TEXT application_url "nullable"
#         BLOB embedding "float32 x 384, nullable until embedded"
#         TIMESTAMP created_at "DEFAULT CURRENT_TIMESTAMP"
#     }
# 
# """
# 
# render_mermaid(diagram_7_text)
#

"""## Diagram 8"""

# Commented out IPython magic to ensure Python compatibility.
# # Paste your Mermaid instructions for Diagram 8 between the triple quotes
# diagram_8_text = """
# %% Resume-to-Job - Current Deployment (local Docker / docker-compose)
# flowchart TB
#     subgraph host["Developer host / local machine"]
#         browser["Browser<br/>localhost:8501"]
#         subgraph compose["docker compose"]
#             subgraph container["app container (python:3.11-slim)"]
#                 st["Streamlit server<br/>:8501 on 0.0.0.0"]
#                 code["application code (src/)"]
#                 model["bundled model<br/>models/all-MiniLM-L6-v2"]
#             end
#         end
#         vol_data[("bind mount: ./data<br/>jobs.sqlite3")]
#         vol_local[("bind mount: ./local<br/>docs / notes")]
#     end
# 
#     gemini["Gemini API<br/>(external, BYOK)"]
#     arbeitnow["LinkedIn data<br/>(Power Automate / API)"]
# 
#     browser -->|HTTP| st
#     st --- code
#     code --- model
#     container --> vol_data
#     container --> vol_local
#     code -->|HTTPS| gemini
#     code -->|HTTPS| arbeitnow
# 
# """
# 
# render_mermaid(diagram_8_text)
#

"""## Diagram 9"""

# Commented out IPython magic to ensure Python compatibility.
# # Paste your Mermaid instructions for Diagram 9 between the triple quotes
# diagram_9_text = """
# %% Resume-to-Job - Proposed Azure Deployment + CI/CD + MLOps (Week 10 target)
# %% Recommendation: keep the Docker image, run it on Azure Container Apps.
# flowchart TB
#     dev["Team developers"]
#     users["End users / faculty"]
# 
#     subgraph gh["GitHub"]
#         repo["Repository: resume-to-job"]
#         subgraph actions["GitHub Actions (CI/CD)"]
#             ci["CI: ruff + pytest +<br/>build Docker image"]
#             cd["CD: push image + deploy"]
#         end
#     end
# 
#     subgraph azure["Microsoft Azure"]
#         acr["Azure Container Registry<br/>(versioned images)"]
#         subgraph aca["Azure Container Apps"]
#             app["Resume-to-Job container<br/>Streamlit :8501<br/>autoscale 0..N"]
#         end
#         kv["Key Vault<br/>(Gemini key, secrets)"]
#         storage[("Azure Files or Postgres<br/>jobs + embeddings")]
#         insights["Application Insights<br/>+ Log Analytics"]
#     end
# 
#     subgraph mlops["MLOps assets"]
#         registry["Model + data registry<br/>(MiniLM version, eval sets)"]
#         experiments["Experiment tracking<br/>(prompt / embedding A-B results)"]
#     end
# 
#     gemini["Gemini API (external)"]
#     arbeitnow["LinkedIn data (Power Automate / paid API)"]
# 
#     dev -->|git push / PR| repo
#     repo --> ci
#     ci --> cd
#     cd -->|docker push| acr
#     acr -->|pull image| app
#     cd -->|az containerapp update| app
# 
#     app --> kv
#     app --> storage
#     app -->|telemetry| insights
#     app -->|HTTPS| gemini
#     app -->|HTTPS| arbeitnow
#     users -->|HTTPS| app
# 
#     registry -. feeds .-> app
#     experiments -. informs .-> registry
#     ci -. runs eval .-> experiments
# 
# """
# 
# render_mermaid(diagram_9_text)
#